from trainDepartureViewer.autz.credentials import TOKEN


TRAIN_GATEWAY_URL='https://gateway.apiportal.ns.nl/reisinformatie-api/api/v2/'
PAYLOAD='payload'
DEPARTURES='departures'
PLANNED_DATE_TIME='plannedDateTime'
DIRECTION='direction'
PLANNED_TRACK='plannedTrack'
TRAIN_CATEGORY='trainCategory'
INTER_CITY='Intercity'
IC='IC'
SPRINTER='Sprinter'
SPR='SPR'
KEY_ERROR='Api key changed'
CONNECTION_TIMEOUT='Connection timout has occured'
BAD_GATEWAY='Unable to connect to train gateway'
USERNAME='username'
PASSWORD='password'
UNAUTHORIZED_WARNING='The credentials entered are not valid'
BAD_TOKEN_REQUEST='Please provide username and password in the post request'
STATION='?station='
STATION_CODE='stationCode'
STATION_CODE_MISSING='Please provide a valid stationCode'
CODE='code'
NAMEN='namen'
LANG='lang'
STATIONS='stations'
TOKEN='Token '
TOKEN_NOT_FOUND='Please provide a valid token'